export default{
    icNavHome: require('../assets/images/navbar_home.png'),
    icNavFavorite: require('../assets/images/nabfavorite.png'),
    icNAbCategory: require('../assets/images/checkout.png'),
    icNabProfile: require('../assets/images/nabuser.png'),
    icClose_image : require('../assets/images/close.png'),
    icMenu: require('../assets/images/menu.png'),
    iciconsmenu: require('../assets/images/iconsmenu.png'),
    ingotoLogin: require('../assets/images/gotoLogin.png'),
    insignup: require('../assets/images/signup.png'),
    icfacebook: require('../assets/images/facebookk.png'),
    icDrawer_logo: require('../assets/images/PDUEEYS.jpg'),
    icrefresh: require('../assets/images/refresh.png'),
    icCalender: require('../assets/images/Calendars.png'),
    icAddCustomer: require('../assets/images/add_cust.png'),
    icAddToCart: require('../assets/images/addtocart.png'),
    icAddFavorite: require('../assets/images/addfavotite.png'),
    icedit: require('../assets/images/edit.png'),
    icDeleteItem: require('../assets/images/delete.png'),
    icfavForRemove: require('../assets/images/favForRemove.png'),
    icuser: require('../assets/images/BookCreator.webp'),
    icgoogle: require('../assets/images/Google-Symbol.png'),
    
    icAddfavorite: require('../assets/images/maps-and-flags.png'),
    ////////////////////////////////////
    icEditProfile: require('../assets/images/output-edit_profile.gif'),
    icContactUs: require('../assets/images/output-contact_us.gif'),
    icPassword: require('../assets/images/output-password.gif'),
    icLogOut: require('../assets/images/output-logout.gif'),
    icAboutUs: require('../assets/images/output-about_us.gif'),
    icDummyUser: require('../assets/images/dummy_user.png'),
    icbackForward: require('../assets/images/output-back.gif'),
    icbackNoraml: require('../assets/images/back.webp'),
    icback: require('../assets/images/output-back.gif'),
    icfirstss: require('../assets/images/ft_screen.jpg'),
    icStaff: require('../assets/images/output-onlinegiftools.gif'),
    icRoute: require('../assets/images/output-route.gif'),
    icTimeline: require('../assets/images/output-timeline.gif'),
    icSalary: require('../assets/images/output-salary.gif'),
    icInvoice: require('../assets/images/output-Invoice.gif'),
    icJoining: require('../assets/images/output-Joining.gif'),
    ictTotal_staff: require('../assets/images/output-total-staff.gif'),
    icBook: require('../assets/images/output-class.gif'),
    icClass: require('../assets/images/output-add_book.gif'),
}